# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021 Giulio Benetti <giulio.benetti@micronovasrl.com>

obj-y += ../../sunxi/board.o
# sun7i is compatible with sun5i
obj-y += ../../sunxi/dram_sun5i_auto.o
obj-y += s027_3.o
